#[mainSections]
#  mainSections = [ 'posts' ]

[showtoc]
showtoc = true

[profileMode]
enabled = true
subtitle = 'Technical writer, freelance technology journalist, FOSS advocate'

[[profileMode.buttons]]
name = 'Posts'
url = '/posts'

[[profileMode.buttons]]
name = 'Blog'
url = '/blog'

[[profileMode.buttons]]
name = 'About'
url = '/about'

[homeInfoParams]
Title = 'Home'
Content = 'Technical writer, freelance technology journalist, FOSS advocate'

[[socialIcons]]
name = "linkedin"
url = "https://www.linkedin/in/jccpalmer"

[[socialIcons]]
name = "codeberg"
url = "https://www.codeberg.org/jccpalmer"

[showPostsOnHomePage]
enabled = false

[comments]
enabled = true
